/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import * as React from 'react';
import {Platform, View, TouchableOpacity, Text, StyleSheet} from 'react-native';
import {ManageWallpaper, TYPE} from 'react-native-manage-wallpaper';

export default class App extends React.Component<{}> {
  _setWallpaper = type => {
    const uri = {
      home:
        'https://i.pinimg.com/originals/76/5e/1d/765e1dc8cb1cc115fb3b0b39a895fdeb.jpg',
      lock: 'https://pbs.twimg.com/media/DLHyvP1VYAA4eCA.jpg',
      both: 'https://images.unsplash.com/photo-1473081556163-2a17de81fc97',
    };
    ManageWallpaper.setWallpaper(
      {
        uri: uri[type],
      },
      res => {
        console.warn('check', res);
      },
      type,
    );
  };

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          onPress={() => this._setWallpaper(TYPE.HOME)}>
          <Text style={styles.text}>Change Home Wallpaper</Text>
        </TouchableOpacity>
        {Platform.Version >= 24 && (
          <>
            <TouchableOpacity
              style={styles.button}
              onPress={() => this._setWallpaper(TYPE.LOCK)}>
              <Text style={styles.text}>Change Lock Wallpaper</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.button}
              onPress={() => this._setWallpaper(TYPE.BOTH)}>
              <Text style={styles.text}>Change Both Wallpaper</Text>
            </TouchableOpacity>
          </>
        )}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  button: {
    paddingHorizontal: 30,
    paddingVertical: 8,
    marginBottom: 24,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
  },
  text: {
    fontSize: 20,
    margin: 10,
    textAlign: 'center',
    color: '#FFFFFF',
  },
});
